openapi: 3.0.0
info:
  title: API Test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /customer:
    get:
      summary: Get Customer Info
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    description: Customer name
                  crid:
                    type: string
                    description: Customer Routing ID
      description: Get information for the current customer.
components:
  schemas: {}
